name: Terraform Tests

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-tests:
    uses: ./.github/workflows/reusable-terraform-test.yml
    with:
      modules_root: modules
      terraform_version: 1.9.8
      comment_on_pr: true
    secrets: inherit